name: build

on:
  push:
    tags-ignore: 'plugins*'
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: Test
      run: dotnet test -c Release --no-build --verbosity normal
    - name: Pack CA.LoopControlPluginBase
      run: dotnet pack CA.LoopControlPluginBase -c Release -o out
    - name: Pack CA_DataUploaderLib
      run: dotnet pack CA_DataUploaderLib -c Release -o out
    - name: make generated nuget packages available as workflow artifacts too
      uses: actions/upload-artifact@v2
      with:
        name: nugetpackages
        path: out
    - name: Push generated package to nuget
      if: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/master') || startsWith(github.ref, 'refs/tags') }}
      run: dotnet nuget push out/*.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.CA_NUGET_PACKAGES_KEY }}

