name: main build

on:
  push:
    tags-ignore: 'plugins*'
    paths-ignore: 'CA.LoopControlPluginBase/**'
    branches: [ master ]
  pull_request:
    branches: [ master ]
    paths-ignore: 'CA.LoopControlPluginBase/**'

jobs:
  nuget-packages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1.8.2
      with:
        dotnet-version: '6.0'
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: Test
      run: dotnet test -c Release --no-build --verbosity normal
    - name: Pack CA_DataUploaderLib
      run: dotnet pack CA_DataUploaderLib -c Release -o out
    - name: make generated nuget packages available as workflow artifacts too
      uses: actions/upload-artifact@v2
      with:
        name: nugetpackages
        path: out
    - name: Push generated package to nuget
      if: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/master') || startsWith(github.ref, 'refs/tags') }}
      run: dotnet nuget push out/*.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.CA_NUGET_PACKAGES_KEY }}
  main-executable: # this creates plenty of files and takes plenty of time, only do it for tags
    if: ${{ startsWith(github.ref, 'refs/tags') }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1.8.2
      with:
        dotnet-version: '6.0'
    - name: Generate DataUploader - linux-x64
      run: dotnet publish CA_DataUploader -c Release -o out/linux-x64/uploader -r linux-x64 -p:PublishSingleFile=true
    - name: Generate DataUploader - linux-arm
      run: dotnet publish CA_DataUploader -c Release -o out/linux-arm/uploader -r linux-arm -p:PublishSingleFile=true
    - name: Generate DataUploader - osx-x64
      run: dotnet publish CA_DataUploader -c Release -o out/osx-x64/uploader -r osx-x64 -p:PublishSingleFile=true
    - name: Generate DataUploader - win-arm
      run: dotnet publish CA_DataUploader -c Release -o out/win-arm/uploader -r win-arm -p:PublishSingleFile=true
    - name: Generate DataUploader - win-x64
      run: dotnet publish CA_DataUploader -c Release -o out/win-x64/uploader -r win-x64 -p:PublishSingleFile=true
    - name: Generate DataUploader - win-x86
      run: dotnet publish CA_DataUploader -c Release -o out/win-x86/uploader -r win-x86 -p:PublishSingleFile=true
    - name: Install zip
      uses: montudor/action-zip@v0.1.1
    - name: Zip - linux-x64
      run: zip -qq -r CA_DataUploader-linux-x64.zip uploader
      working-directory: 'out/linux-x64'
    - name: Zip - linux-arm
      run: zip -qq -r CA_DataUploader-linux-arm.zip uploader
      working-directory: out/linux-arm
    - name: Zip - osx-x64
      run: zip -qq -r CA_DataUploader-osx-x64.zip uploader
      working-directory: out/osx-x64
    - name: Zip - win-arm
      run: zip -qq -r CA_DataUploader-win-arm.zip uploader
      working-directory: out/win-arm
    - name: Zip - win-x64
      run: zip -qq -r CA_DataUploader-win-x64.zip uploader
      working-directory: out/win-x64
    - name: Zip - win-x86
      run: zip -qq -r CA_DataUploader-win-x86.zip uploader
      working-directory: out/win-x86
    - name: Release
      uses: softprops/action-gh-release@b7e450da2a4b4cb4bfbae528f788167786cfcedf
      with:
        files: 'out/**/*.zip'
        draft: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - uses: release-drafter/release-drafter@e5ccf147077e46b0225a80bbe314d795d77bb7a2
      with:
        name: ${{ env.RELEASE_VERSION }}
        tag: ${{ github.ref }}
        version: ${{ env.RELEASE_VERSION }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
