name: main build

on:
  push:
    tags-ignore: 'plugins*'
    paths-ignore: 'CA.LoopControlPluginBase/**'
    branches: [ master ]
  pull_request:
    branches: [ master ]
    paths-ignore: 'CA.LoopControlPluginBase/**'

jobs:
  nuget-packages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: Test
      run: dotnet test -c Release --no-build --verbosity normal
    - name: Pack CA_DataUploaderLib
      run: dotnet pack CA_DataUploaderLib -c Release -o out
    - name: make generated nuget packages available as workflow artifacts too
      uses: actions/upload-artifact@v2
      with:
        name: nugetpackages
        path: out
    - name: Push generated package to nuget
      if: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/master') || startsWith(github.ref, 'refs/tags') }}
      run: dotnet nuget push out/*.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.CA_NUGET_PACKAGES_KEY }}
  main-executable: # this creates plenty of files and takes plenty of time, only do it for tags
    if: ${{ startsWith(github.ref, 'refs/tags') }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Generate DataUploader - linux-x64
      run: dotnet publish CA_DataUploader -c Release -o tmp/uploader/linux-x64 -r linux-x64 -p:PublishSingleFile=true
    - name: Generate DataUploader - linux-arm
      run: dotnet publish CA_DataUploader -c Release -o tmp/uploader/linux-arm -r linux-arm -p:PublishSingleFile=true
    - name: Generate DataUploader - osx-x64
      run: dotnet publish CA_DataUploader -c Release -o tmp/uploader/osx-x64 -r osx-x64 -p:PublishSingleFile=true
    - name: Generate DataUploader - win-arm
      run: dotnet publish CA_DataUploader -c Release -o tmp/uploader/win-arm -r win-arm -p:PublishSingleFile=true
    - name: Generate DataUploader - win-x64
      run: dotnet publish CA_DataUploader -c Release -o tmp/uploader/win-x64 -r win-x64 -p:PublishSingleFile=true
    - name: Generate DataUploader - win-x86
      run: dotnet publish CA_DataUploader -c Release -o tmp/uploader/win-x86 -r win-x86 -p:PublishSingleFile=true
    - name: Zip - linux-x64
      uses: montudor/action-zip@c25e01d7489d0274569440a2f0281b4569df16bc
      with:
        args: zip -qq -r CA_DataUploader-linux-x64.zip tmp/uploader/linux-x64
    - name: Zip - linux-arm
      uses: montudor/action-zip@c25e01d7489d0274569440a2f0281b4569df16bc
      with:
        args: zip -qq -r CA_DataUploader-linux-arm.zip tmp/uploader/linux-arm
    - name: Zip - osx-x64
      uses: montudor/action-zip@c25e01d7489d0274569440a2f0281b4569df16bc
      with:
        args: zip -qq -r CA_DataUploader-osx-x64.zip tmp/uploader/osx-x64
    - name: Zip - win-arm
      uses: montudor/action-zip@c25e01d7489d0274569440a2f0281b4569df16bc
      with:
        args: zip -qq -r CA_DataUploader-win-arm.zip tmp/uploader/win-arm
    - name: Zip - win-x64
      uses: montudor/action-zip@c25e01d7489d0274569440a2f0281b4569df16bc
      with:
        args: zip -qq -r CA_DataUploader-win-x64.zip tmp/uploader/win-x64
    - name: Zip - win-x86
      uses: montudor/action-zip@c25e01d7489d0274569440a2f0281b4569df16bc
      with:
        args: zip -qq -r CA_DataUploader-win-x86.zip tmp/uploader/win-x86
    - name: upload zip file as workflow artifacts
      uses: actions/upload-artifact@v2
      with:
        name: zipfiles
        path: *.zip
        retention-days: 5 #make sure these don't stay a long time around, final output is the release
